后端处理实现
InCar/methane-po pull request #4
Opened 2020-01-16 01:21 UTC by ALiXiaolan

1、配置GRPC监听端口、配置收发器选项
2、实现vehicle部分代码

2020-01-16 01:25 UTC, ALiXiaolan commented
#12

2020-01-16 05:41 UTC, ALiXiaolan commented
Incar/ methane #12

2020-01-16 05:46 UTC, ALiXiaolan commented
InCar/methane#12

2020-01-16 07:48 UTC, AceBear requested changes
### 至少需要补充3个单元测试

+ Mock一个IReceiver, 创建一个HelloServiceV1的客户端, 来验证TransceiverGRPC的实现是正确的
+ Mock一个IMonitor, 创建一个CountServiceV1的客户端,来验证MonitorService的实现是正确的
+ 以不同参数调用几次VehicleMgr.OnReceive方法,再调用VehicleMgr.GetXXX方法，验证VehicleMgr的实现是正确的

### 考虑再补充一个多线程并发单元测试
以多线程方式调用VehicleMgr.OnReceive，验证VehicleMgr的实现是多线程安全的

2020-01-16 07:48 UTC, AceBear commented on src/main/java/com/incarcloud/methane/comm/TransceiverFactory.java
> +    private int transceiver;
配置文件中使用整数,使用方不容易一眼看出来 1 2 3分别代表什么含义，考虑改为使用字符串

2020-01-16 07:48 UTC, AceBear commented on src/main/java/com/incarcloud/methane/mgr/VehicleBiz.java
> +        msgCount++;
这里是否会存在多线程并发计数丢失问题？

2020-01-16 07:48 UTC, AceBear commented on src/main/java/com/incarcloud/methane/mgr/VehicleMgr.java
> +                return 1;
收到一条消息，计数值加1的逻辑在什么地方？

2020-01-19 07:39 UTC, AceBear requested changes
改进一下日志相关的部分

2020-01-19 07:39 UTC, AceBear commented on src/main/java/com/incarcloud/methane/comm/Transceiver.java
> +        System.out.println("---onReceive-----" + input.getVin());
已经集成了sl4j2的日志，如果要输出日志，改为使用sl4j2 的日志完成

2020-01-19 07:39 UTC, AceBear commented on src/main/java/com/incarcloud/methane/comm/TransceiverFactory.java
> +            //ts = new TransceiverRocketMQ;
不支持的抛出异常,这样注释掉会导致返回一个null，然后在外面调用的地方得到了个NullReference的异常，相比明确的“不支持”异常，NullReference异常让人第一眼不知道原因

2020-01-19 07:39 UTC, AceBear commented on src/main/java/com/incarcloud/methane/Host.java
> -    // TODO: From configuration
类似这种标记有 TODO的地方，如果已经完成，去掉TODO，可以保留TODO后的注释内容
如果没有完成，比如有的TODO是要求记个日志，完成记日志的实现

2020-01-19 08:16 UTC, merged